name: Package Extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUBWORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependacies
        run: npm install

      - name: Build Compass into an Extension
        run: |
              npm run build
              runTimestamp="$(date +%D)_$(date +%H)-$(date +%M)-$(date +%S)"
              mkdir -p extension/builds/
              mv dist/* extension/builds/
              cp -r extension/base/* extension/builds/
      
      - name: Create artifact...
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: ./extension/builds/
