name: Release
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Should publish to github releases'
        required: true
        default: 'off'
      version:
        description: 'The version to be updated in all files'
        required: true
        default: '0.0.0'
      prerelease:
        description: 'If it should be publish as a prerelease'
        required: true
        default: 'off'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout...
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: cd react && yarn

      - name: Change version
        run: node ./scripts/version.js ${{ github.event.inputs.version }}

      - name: Upload changes...
        uses: EndBug/add-and-commit@v7
        with:
          author_email: dothq-robot@users.noreply.github.com
          message: 'ðŸ”– Bump version to ${{ github.event.inputs.version }}'

      - name: Build
        run: yarn build:prod && cp -r ../extensions/official/**/* dist

      - name: Compress
        run: |
          cd dist 
          zip -r ntp .
          cd ..
          mv dist/ntp.zip .

      - name: Create release
        id: create_release
        if: github.event.inputs.release == 'on'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: 'v${{ github.event.inputs.version }}'
          release_name: Release v${{ github.event.inputs.version }}
          body: ''
          draft: false
          prerelease: github.event.inputs.prerelease == 'on'

      - name: Upload Release Asset
        id: upload-release-asset
        if: github.event.inputs.release == 'on'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./react/ntp.zip
          asset_name: ntp.zip
          asset_content_type: application/zip
